### ISSUE TITLE
Some ideas in Logger graph

### ISSUE THREAD

**Issue by proasnet** [fredlcore/BSB-LAN#344]
Hi, as I wrote yesterday, my ideas is some minor adjustments, as is in my picture.
![obrázok](https://user-images.githubusercontent.com/76579362/110233503-a5137c80-7f24-11eb-9107-c8be6b2c15e9.png)

**Comment by fredlcore** [comment]
Negative scale has been fixed, not sure about the possibility of the D3 framework to provide a right scale. As for parameter numbers, I can have a look...

**Comment by dukess** [comment]
Instead right scaling i can propose horizontal lines:
![изображение](https://user-images.githubusercontent.com/5211561/111115282-6e1d1680-8575-11eb-9687-bfdb471d7dde.png)

**Comment by fredlcore** [comment]
Horizontal lines would be nice!

**Comment by dukess** [comment]
https://github.com/fredlcore/BSB-LAN/pull/349

**Comment by fredlcore** [comment]
Thanks! Will close this now as I think this is as far as we can get. If there's anything else or new, feel free to re-open!

**Comment by fredlcore** [comment]
Now that I have a closer look at your image, I can see that you have an option to select the date, that is pretty cool!
Could we do something like displaying just the values of the last week by default? Because now, the data is always loaded completely into the browser (which can take quite a long time with longer logs). 
I guess we would have to add an option to the 'D' parameter for that. But on the other hand, we don't always have the (correct) date in the logfile (PPS only has day of week, so we have to use the year 2018).
Or maybe rather than taking a date, we could add a parameter to only send the last X lines of log file. But then we don't beforehand, how many lines there are in a log file. Hm... Maybe too complicated ;)...

**Comment by dukess** [comment]
>Could we do something like displaying just the values of the last week by default? Because now, the data is always loaded completely into the browser (which can take quite a long time with longer logs).

i just added 
```
        data = data.filter(function(d) {
          return (d.Date >= cutoffDateS && d.Date <= cutoffDateE);
        });

```
after 
```
data.forEach(function(d) {
          d.Date = parseDate(d.Date);
          d.Value = +d.Value;
        });
```
block.
Date values will be got from date picker
      var cutoffDateS = new Date(gemById('startd3date').value + "T00:00:00");
      var cutoffDateE = new Date(gemById('endd3date').value + "T23:59:59");

where gemById() is alias for getElementById() but we can get current date and calculate week ago.

Unfortunately we must read whole file in any case. But browser can cache datalog if we reading it through external web server.

**Comment by proasnet** [comment]
Yes. This is nice.
I found the next logging problem.
I have a pen with Relative output, thus is power of burner in %, now I dont
know a number, I can write later. In night is this parameter iddle and have
not zero value, but --. Graphic loger can not refresh in morning drawing
and not continue.

Dne po 15. 3. 2021 8:03 uživatel Serguei S. Dukachev <
***@***.***> napsal:

**Comment by dukess** [comment]
Can you look in browser console? It is possible than d3 crashed when it received "---" instead numerical value.

**Comment by fredlcore** [comment]
Can we close this?

**Comment by proasnet** [comment]
Yes of course. Thank you very much for your work. With regards.

Dne st 31. 3. 2021 0:28 uživatel fredlcore ***@***.***>
napsal:
