### ISSUE TITLE
Idea - different sample frequncy for each sensor

### ISSUE THREAD

**Issue by Charodej** [fredlcore/BSB-LAN#365]
An idea that would be great to integrate - different sample frequency for the parametres on some group types or by each individual.
I would appreciate to use that for sensors directly connected to due - more frequent and sensors connected to the Heater controller - les frequent.
Right now it can be only set for all of them one value.

**Comment by fredlcore** [comment]
That would mean we would have to store a polling interval for each parameter in the EEPROM. This will be only necessary for a limited user group, because if you use a home automation system, you can set the polling interval for each parameter there. That's why such a feature is unlikely to be implemented by us. You can still code your own routines in the _custom.h files.
