### ISSUE TITLE
[FEATURE REQUEST] Report RSSI

### ISSUE THREAD

**Issue by designer2k2** [fredlcore/BSB-LAN#455]
**Is your feature request related to a problem? Please describe.**
I would like to know the RSSI (Wifi Signal Strength) over time, basically to see if the signal is constant or maybe fluctuating during the day.

**Describe the solution you'd like**
Getting it via MQTT or being able to query it like any other parameter. 
Maybe like the OneWire that start at 20000 this "internal" information could start at 30000?

The ESPhome devices have a function like this: https://esphome.io/components/sensor/wifi_signal.html

**Describe alternatives you've considered**
If i could see the RSSI on the setting page (/C) maybe below the uptime this would also work, but not as good.

**Describe your own contribution**
I could help to test it.  But for more i would need a hint on how to implement it as im quite lost in the code.

The Serial debugging gives the RSSI: https://github.com/fredlcore/BSB-LAN/blob/f83c20b8c962adb68e1b7cfd3fcda3f7bef9ac76/BSB_LAN/BSB_LAN.ino#L6925

**Additional context**
This only makes sense on WIFI enabled devices.

**Comment by DE-cr** [comment]
@designer2k2, I see how this could be useful.
Have you checked whether you could easily receive this information from your WLAN router instead?
Displaying the RSSI on the /C page should be really simple to implement. It that would be good enough for you, let me know if I should do an implementation proposal.
Creating a fake BSB parameter would be more work, and might require some design decisions which I'd rather leave up to @fredlcore.

**Comment by fredlcore** [comment]
I'm relatively strict when it comes to adding new features due to the limited amount of flash memory we have on the Due and eventually also on the ESP32 (which has more Flash, but half of it is reserved to perform OTA updates and the code in general is much larger than for the Due due to the more extensive framework), and especially when it comes to features that are not directly connected with the core functionality. 
The RSSI values are usually only needed once when you setup the device to figure out a suitable place, so a permanent function for that would not be necessary. Additionally, you can get this value usually from your router, and if not, you can add the suggested code to BSB_LAN_custom.h and send it to the debug output, that's what the custom code function is designed for.
