### ISSUE TITLE
[FEATURE REQUEST] add a platformio.ini to build the project with PlatformIO

### ISSUE THREAD

**Issue by henrythasler** [fredlcore/BSB-LAN#467]
**Is your feature request related to a problem? Please describe.**
There is no out-of-the-box solution to build BSB-LAN with PlatformIO. I had to create my own config-file.

**Describe the solution you'd like**
I want to give platformio users a headstart by providing a valid `platformio.ini` with several platforms to work out-of-the-box w/o the need to delete folders and so on after cloning/opening the BSB-LAN project.

**Describe alternatives you've considered**
People could import the folder and add their custom config.

**Describe your own contribution**
I can provide a PR with 1-2 platforms that can be extended with other platforms later.

**Additional context**
(none)

**Comment by fredlcore** [comment]
This was discussed here before: https://github.com/fredlcore/BSB-LAN/issues/465
I'm not going to add this as a core file to the repository because it would require adjustments every time the syntax changes (just happened with `src_filter`) and it also depends on the microcontroller used (some ESP32 run well with 921000, others just with half of it). 
I would suggest you add a discussion topic where interested users can post their configurations, but it's not going to be added to the repo as its own file.
