### ISSUE TITLE
[FEATURE REQUEST] Sending more than 40 register values to MQTT ?

### ISSUE THREAD

**Issue by raa-hasel** [fredlcore/BSB-LAN#597]
Is there a possibility to send more than 40 register values to the MQTT broker ?
Why do the register values to be sent to MQTT broker also have to be stored locally ?
Wouldn't it make sense to separate data to be stored locally and data to send to MQTT if necessary ?

Best regards
RalphAndreas

**Comment by fredlcore** [comment]
The values are not necessarily stored locally, but the parameters have to be stored in some kind of variable which in C++ is usually an array of a fixed length. You should be able to add more parameters by increasing the size of the array accordingly, but unless you use relatively long intervals, I would not recommend that because each parameter takes up to 2 seconds to be queried from the heater. So with 40 parameters you are already above one minute. If your polling interval is one minute or less, BSB-LAN will be practically doing nothing else than polling values from the heater. 
And no, there is no way to have individual polling intervals for individual parameters and I'm not planning on implementing something like that. That can be done through your home automation software by polling each set of parameters in a defined interval using HTTP requests which will get you JSON structures which most home automation systems should be able to parse easily.
