### ISSUE TITLE
[BUG]?: calculation of free space in filesystem

### ISSUE THREAD

**Issue by DE-cr** [fredlcore/BSB-LAN#652]
I understand there's the possibility to include an SD card in an ESP32 system, and BSB-LAN allows to choose whether to use an ESP32's internal flash memory or an included SD card for file storage. In BSB-LAN.ino, there's a couple of locations where the available filesystem space is calculated like this:
```
#ifdef ESP32
    totalBytes()-usedBytes();
#else
    SDCard.vol()->freeClusterCount() * SDCard.vol()->bytesPerCluster();
#endif
```
Is this correct in all configurations?

**Comment by fredlcore** [comment]
It should as it has been correct all this while on both NodeMCU and Olimex. Now that you can use SD_MMC and SPI-based SD-card readers on NodeMCU, the former case should still be working because it is the same as the Olimex, so the only issue could be with NodeMCUs using SPI-based card readers. Since compilation works fine, I would assume it's not an issue. I don't have time to check if the libraries are the same, but feel free to do so. Unless there is an actual bug here, I'd close this for now.
