### ISSUE TITLE
[QUESTION] LMU34

### ISSUE THREAD

**Issue by GSzabados** [fredlcore/BSB-LAN#658]
Is there any chance that BSB-LAN is working with an LMU34?

https://sid.siemens.com/v/u/A6V10283859

**Comment by fredlcore** [comment]
Unfortunately not, the LMU34 is an OpenTherm controller.

**Comment by GSzabados** [comment]
Thanks Fred! I really appreciate the prompt answer!

**Comment by fredlcore** [comment]
Most welcome. Do you have the LMS34 in one of your heating systems? From what year roughly is it? The controller looks kind of "new", but the only other OpenTherm controller I know of (LMU64) is almost 20 years in the market, and then Siemens seemed to have switched to BSB...

**Comment by fredlcore** [comment]
Ah, I know him, have been in touch with him via e-mail. I'm also wondering about the age of the controller. As it's an OpenTherm controller, it can be used with the GTW16 OpenTherm-to-IDA gateway, in a similar way as the IDA can also be used with the GTW17 BSB-to-IDA gateway. But the manual you linked above is from 2018. So I'm not sure if this is just a revision date or if it really is a rather new controller. Would be strange for Siemens to switch from BSB/LPB to OpenTherm again which they used for room units in the LMU54/64 controllers which are almost 20 years old. The GTW16/GTW17 have been produced by Brötje/BDR Thermea in order to connect to their older models, it's not made by Siemens.
The WHBS doesn't seem to be sold in Germany, I could only find links to Eastern European sites so far, that's why I haven't run into it until now...

**Comment by GSzabados** [comment]
The Polish manual which I found was from 2019, I just linked that English, because that is more understandable.  My guess these models are for cheaper replacements for old gas heaters. Like you do not need a really expensive heater for a single (small) flat, where you have only a single heating circuit and you don't have a DHW storage tank, but direct DHW, and you would control the temperature with a single thermostat. 
Eastern Europe it was quite common, and I think it is still, for multi flat houses, each flat has it's own chimney and heater, originally with circulation gas heater, and now as regulation requires it, with condensation heater. Probably it was a solution for the manufacturer to sell more units on the low end as well.

**Comment by fredlcore** [comment]
Yes, we have similar approaches in Germany as well, also with "cheaper" controllers etc., it's just that this specific model was unknown to me, and the fact that Siemens creates an OpenTherm controller for that purpose is surprising because they're not necessarily cheapter...
