### ISSUE TITLE
[BUG] Changes to the timer program for more than one switch-on phase are not accepted via mqtt / web interface

### ISSUE THREAD

**Issue by realEntwickler** [fredlcore/BSB-LAN#685]
**Version of the Arduino IDE**  
2.3.4

**Version of the ESP32 or Arduino framework**  
3.0.7

**BSB-LAN Version**  
4.2.38-20241207024203

**Architecture**  
OLIMEX ESP32-EVB

**Bus system**  
BSB

**Describe the bug**  
If I only define an on and off phase in my timer program for TWW or a heating circuit, BSB-LAN accepts the data and sends it on to the heating control system. If I now set two on and off phases either via MQTT or web interface, the changes are not adopted and the previous setting is retained. However, if I carry out such programming via the control panel on the heater itself, BSB-LAN displays these values correctly in the timer program.

**To Reproduce**  
1. Go to 'Heating Functions / any timer program '
2. Select e.g. '501 timer program 1 - Monday'
3. Specify programming with two on and off phases
4. Press Set and the previous setting is retained.

**Log files - Bug reports without log files will be closed**  
I will submit a log file later.

**Expected behavior**  
BSB-LAN should take over the programming with two on and off phases.

**Screenshots**  
/

**Desktop (if applicable, please complete the following information):**  
 - OS: Windows 11 Pro
 - Browser: Mozilla Firefox
 - Browser version: 133.0

**Additional context**  
/

**Attach your BSB_LAN_config.h file to your bug report (remove any confidential information if necessary). Do not ZIP or otherwise compress it. Bug reports without this file attached will be closed immediately.**
[BSB_LAN_config.h.txt](https://github.com/user-attachments/files/18066220/BSB_LAN_config.h.txt)

**Comment by fredlcore** [comment]
For URL-transmitted parameters, you have to use a `_` as a separator between the three time programs. For MQTT, both `_` and space should do fine. I had changed this to space-only a short while ago, but I tested it only with JSON, not with URL-encoding. This of course sends `%20` instead of space, so the code didn't work here. Now I changed the webinterface to convert space to `_`, but spaces are still accepted for those modes of transmissions where they are actually transmitted unchanged.
